export const dialogPresets = Object.freeze({
  resetSimulasi: {
    variant: 'danger',
    title: 'Reset seluruh simulasi?',
    description: 'Draft lokal dan seluruh entri simulasi akan dihapus.',
    confirmLabel: 'Reset Simulasi',
    cancelLabel: 'Batal',
  },
  hapusEntri: {
    variant: 'danger',
    title: 'Hapus entri?',
    description: 'Entri yang dihapus tidak dapat dipulihkan.',
    confirmLabel: 'Hapus',
    cancelLabel: 'Batal',
  },
  keluarTanpaSimpan: {
    variant: 'warning',
    title: 'Keluar tanpa menyimpan?',
    description: 'Perubahan yang belum disimpan akan hilang.',
    confirmLabel: 'Keluar',
    cancelLabel: 'Tetap di sini',
  },
  simpanScope1: {
    variant: 'info',
    title: 'Simpan data Scope 1?',
    description: 'Pastikan data konsumsi BBM dan periode sudah benar.',
    confirmLabel: 'Simpan Data',
    cancelLabel: 'Periksa Lagi',
  },
  simpanScope2: {
    variant: 'info',
    title: 'Simpan data Scope 2?',
    description: 'Pastikan konsumsi listrik, lokasi, dan periode sudah benar.',
    confirmLabel: 'Simpan Data',
    cancelLabel: 'Periksa Lagi',
  },
  simpanBatchScope1: {
    variant: 'info',
    title: 'Simpan batch Scope 1?',
    description: 'Seluruh baris Scope 1 yang valid dari file ini akan disimpan.',
    confirmLabel: 'Simpan Batch',
    cancelLabel: 'Periksa Lagi',
  },
  simpanBatchScope2: {
    variant: 'info',
    title: 'Simpan batch Scope 2?',
    description: 'Seluruh baris Scope 2 yang valid dari file ini akan disimpan.',
    confirmLabel: 'Simpan Batch',
    cancelLabel: 'Periksa Lagi',
  },
  simpanPlts: {
    variant: 'success',
    title: 'Simpan data PLTS?',
    description: 'Produksi, pemakaian sendiri, dan ekspor akan disimpan untuk periode terpilih.',
    confirmLabel: 'Simpan Data',
    cancelLabel: 'Periksa Lagi',
  },
  simpanSnapshot: {
    variant: 'info',
    title: 'Simpan snapshot simulasi?',
    description: 'Snapshot akan disimpan ke Riwayat Audit lokal dan tidak ikut berubah saat draft diedit.',
    confirmLabel: 'Simpan Snapshot',
    cancelLabel: 'Batal',
  },
  resetDataContoh: {
    variant: 'danger',
    title: 'Reset seluruh data?',
    description: 'Seluruh data akan dikembalikan ke data contoh bawaan.',
    confirmLabel: 'Reset Data',
    cancelLabel: 'Batal',
  },
  resetSimulasiDenganJumlah: (count) => ({
    variant: 'danger',
    title: 'Reset seluruh simulasi?',
    description: 'Draft lokal dan seluruh entri simulasi akan dihapus.',
    details: [`${count} entri simulasi akan dihapus`, 'Profil dan periode dikembalikan ke nilai awal'],
    confirmLabel: 'Reset Simulasi',
    cancelLabel: 'Batal',
  }),
  resetDataDenganJumlah: (count) => ({
    variant: 'danger',
    title: 'Reset seluruh data?',
    description: 'Seluruh data akan dikembalikan ke data contoh bawaan.',
    details: [`${count} log input akan dihapus`],
    confirmLabel: 'Reset Data',
    cancelLabel: 'Batal',
  }),
  hapusEntriBernama: (name) => ({
    variant: 'danger',
    title: 'Hapus entri?',
    description: `Hapus entri ${name}?`,
    confirmLabel: 'Hapus',
    cancelLabel: 'Batal',
  }),
});

export const toastPresets = Object.freeze({
  saveSuccess: { title: 'Data berhasil disimpan', description: 'Dashboard telah diperbarui dengan data terbaru.' },
  saveError: { title: 'Data gagal disimpan', description: 'Periksa data dan koneksi, lalu coba lagi.' },
  uploadSuccess: { title: 'File berhasil diproses', description: 'Data valid siap digunakan.' },
  uploadError: { title: 'File gagal diproses', description: 'Periksa format file dan coba lagi.' },
  deleteSuccess: { title: 'Entri berhasil dihapus', description: 'Daftar dan ringkasan telah diperbarui.' },
  resetSuccess: { title: 'Simulasi berhasil direset', description: 'Draft lokal dan seluruh entri telah dihapus.' },
  resetDataSuccess: { title: 'Data berhasil direset', description: 'Data dashboard telah dikembalikan ke data contoh bawaan.' },
});
