'use client';

import { AlertTriangle, ChevronDown } from 'lucide-react';
import { formatEmission, formatNumber, formatTotalEmission } from '@/lib/calculator/format.js';
import { CALCULATOR_CATEGORIES } from './calculatorConfig';

export default function CalculatorRecap({ profile, entries, summary, days }) {
  const denominator = summary.totalAdditionKg + summary.totalReductionKg;
  const additionShare = denominator > 0 ? summary.totalAdditionKg / denominator * 100 : 0;
  const temporaryEntries = entries.filter(entry => (entry.factorSnapshots || [entry.factorSnapshot]).filter(Boolean).some(factor => factor.status === 'TEMPORARY'));
  return <div className="space-y-5">
    <div className="rounded-2xl border border-blue-100 dark:border-blue-500/20 bg-blue-50 dark:bg-blue-500/10 p-5"><p className="text-xs font-bold uppercase text-blue-700 dark:text-blue-300">Periode simulasi</p><h2 className="mt-1 text-xl font-bold text-slate-900 dark:text-slate-100">{profile.organizationName}{profile.unitName ? ` — ${profile.unitName}` : ''}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{profile.periodStart} sampai {profile.periodEnd} • {days || '—'} hari</p></div>
    <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-rose-100 dark:border-rose-500/20 bg-rose-50 dark:bg-rose-500/10 p-5"><p className="text-xs font-bold uppercase text-rose-700 dark:text-rose-300">Total Penambah</p><p className="mt-2 text-2xl font-black text-rose-900 dark:text-rose-200">+ {formatTotalEmission(summary.totalAdditionKg)}</p></div><div className="rounded-2xl border border-emerald-100 dark:border-emerald-500/20 bg-emerald-50 dark:bg-emerald-500/10 p-5"><p className="text-xs font-bold uppercase text-emerald-700 dark:text-emerald-300">Total Pengurangan</p><p className="mt-2 text-2xl font-black text-emerald-900 dark:text-emerald-200">− {formatTotalEmission(summary.totalReductionKg)}</p></div></div>
    <div className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-slate-300">Emisi Bersih</p><p className="mt-2 text-4xl font-black">{formatEmission(summary.netKg)}</p><p className="mt-3 text-sm text-slate-300">{summary.reductionPct === null ? 'Belum ada sumber penambah untuk menghitung persentase pengurangan.' : `Pengurangan emisi sebesar ${formatNumber(summary.reductionPct)}% dibanding aktivitas normal.`}</p></div>
    <section className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5"><h3 className="font-bold text-slate-900 dark:text-slate-100">Komposisi emisi</h3><div className="mt-4 flex flex-col items-center gap-5 sm:flex-row"><div className="grid size-32 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#f43f5e 0 ${additionShare}%, #10b981 ${additionShare}% 100%)` }} aria-label={`${formatNumber(additionShare)} persen penambah`}><div className="grid size-20 place-items-center rounded-full bg-white dark:bg-slate-900 text-center"><span className="text-xs font-bold text-slate-700 dark:text-slate-300">Penambah<br />{formatNumber(additionShare)}%</span></div></div><div className="w-full space-y-3"><div><div className="mb-1 flex justify-between text-xs"><span>+ Penambah</span><strong>{formatEmission(summary.totalAdditionKg)}</strong></div><div className="h-3 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-rose-500" style={{ width: `${additionShare}%` }} /></div></div><div><div className="mb-1 flex justify-between text-xs"><span>− Pengurangan</span><strong>{formatEmission(summary.totalReductionKg)}</strong></div><div className="h-3 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${100 - additionShare}%` }} /></div></div></div></div></section>
    {temporaryEntries.length > 0 && <details className="rounded-2xl border border-amber-200 dark:border-amber-500/30 bg-amber-50 dark:bg-amber-500/10 p-4"><summary className="flex cursor-pointer list-none items-center gap-2 font-bold text-amber-900 dark:text-amber-200"><AlertTriangle size={18} />{temporaryEntries.length} entri memakai faktor sementara</summary><ul className="mt-3 list-disc space-y-1 pl-6 text-sm text-amber-900 dark:text-amber-200">{temporaryEntries.map(entry => <li key={entry.id}>{entry.label}</li>)}</ul></details>}
    {summary.unavailableCount > 0 && <p className="rounded-xl border border-rose-200 dark:border-rose-500/30 bg-rose-50 dark:bg-rose-500/10 p-4 text-sm font-semibold text-rose-800 dark:text-rose-300">{summary.unavailableCount} entri berstatus “Perlu faktor” tidak dimasukkan dalam total.</p>}
    <section className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5"><h3 className="font-bold text-slate-900 dark:text-slate-100">Rincian per sumber</h3>{entries.length === 0 ? <p className="mt-4 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500 dark:text-slate-400">Belum ada entri untuk direkap.</p> : <div className="mt-4 space-y-3">{CALCULATOR_CATEGORIES.map(category => {
      const categoryEntries = entries.filter(entry => entry.category === category.id && Number.isFinite(entry.kgCo2e));
      if (!categoryEntries.length) return null;
      const total = categoryEntries.reduce((sum, entry) => sum + entry.kgCo2e, 0);
      const share = denominator > 0 ? total / denominator * 100 : 0;
      return <details key={category.id} className="rounded-xl border border-slate-200 dark:border-slate-700"><summary className="flex cursor-pointer list-none items-center gap-3 p-4"><span className={`font-black ${category.kind === 'addition' ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-700 dark:text-emerald-300'}`}>{category.kind === 'addition' ? '+' : '−'}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-800 dark:text-slate-200">{category.title}</span><span className="text-xs text-slate-500 dark:text-slate-400">{categoryEntries.length} entri • {formatEmission(total)}</span></span><span className="text-xs font-bold text-slate-600 dark:text-slate-400">{formatNumber(share)}%</span><ChevronDown size={16} /></summary><div className="border-t dark:border-slate-700 px-4 pb-4"><div className="my-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={category.kind === 'addition' ? 'h-full bg-rose-500' : 'h-full bg-emerald-500'} style={{ width: `${Math.min(100, share)}%` }} /></div>{categoryEntries.map(entry => <div key={entry.id} className="flex justify-between gap-3 py-1 text-xs"><span className="text-slate-600 dark:text-slate-400">{entry.label}</span><strong>{formatEmission(entry.kgCo2e)}</strong></div>)}</div></details>;
    })}</div>}</section>
  </div>;
}
