'use client';

import { MinusCircle, PlusCircle, Scale } from 'lucide-react';
import { formatEmission, formatNumber, formatTotalEmission } from '@/lib/calculator/format.js';

function Content({ summary, days }) {
  return <><div className="rounded-2xl bg-slate-950 p-5 text-white shadow-lg"><p className="text-xs font-bold uppercase tracking-wider text-slate-300">Emisi Bersih</p><p className="mt-2 text-3xl font-black tracking-tight">{formatEmission(summary.netKg)}</p><p className="mt-2 text-xs text-slate-400">Hasil simulasi, tidak mengubah data dashboard.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-2xl border border-rose-100 bg-rose-50 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-rose-700"><PlusCircle size={16} />Total Penambah</div><p className="mt-2 text-xl font-bold text-rose-900">+ {formatTotalEmission(summary.totalAdditionKg)}</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase text-emerald-700"><MinusCircle size={16} />Total Pengurangan</div><p className="mt-2 text-xl font-bold text-emerald-900">− {formatTotalEmission(summary.totalReductionKg)}</p></div></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="flex items-center gap-2 text-sm font-bold text-slate-800"><Scale size={17} />Indikator periode</p><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Pengurangan</dt><dd className="font-semibold">{summary.reductionPct === null ? '—' : `${formatNumber(summary.reductionPct)}%`}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Intensitas per hari</dt><dd className="font-semibold">{days > 0 ? `${formatNumber(summary.netKg / days)} kgCO₂e` : '—'}</dd></div></dl></div></>;
}

export default function CalculatorLiveSummary({ summary, days }) {
  return <><aside className="hidden space-y-4 lg:sticky lg:top-24 lg:block" aria-label="Ringkasan kalkulator"><Content summary={summary} days={days} /></aside><details className="fixed inset-x-3 bottom-3 z-30 rounded-2xl border border-slate-700 bg-slate-950 text-white shadow-2xl lg:hidden"><summary className="flex cursor-pointer list-none items-center justify-between p-4"><span><span className="block text-[10px] font-bold uppercase text-slate-400">Emisi Bersih</span><strong>{formatEmission(summary.netKg)}</strong></span><span className="text-xs font-bold text-blue-300">Buka ringkasan</span></summary><div className="max-h-[65vh] space-y-3 overflow-auto border-t border-slate-700 bg-slate-50 p-3 text-slate-900"><Content summary={summary} days={days} /></div></details></>;
}
