/**
 * Master Registry Fasilitas Operasional & Struktur Cabang Alfamart (SPARTA Sustainability)
 * 
 * Standar Penataan Master Data Berdasarkan Bukti Asli:
 * 1. Struktur Organisasi / Cabang (HO & Branch Offices)
 * 2. Fasilitas Operasional Fisik (HO, Kantor Cabang, DC Kompleks, Toko Ritel Terverifikasi)
 * 3. Plant PLTS (39 entitas mandiri Sungrow / iSolar yang dipetakan ke fasilitas fisik terkait)
 * 4. Aset (Genset Stasioner, Kendaraan Operasional, Meter PLN/PLTS)
 * 
 * Catatan Rekonsiliasi Faktor Emisi Grid Sumatera:
 * - Kepmen ESDM No. 379.K/2021: 0,761 kgCO2e/kWh (disajikan sebagai 0,76).
 * - Referensi KLHK / Laporan Historis tertentu menggunakan pembulatan batas atas 0,77.
 * - SPARTA menggunakan 0,761 (versi ESDM 2021/2026) dengan tagging riwayat audit.
 */

export const FACILITY_TYPES = {
  HO: { code: 'HO', label: 'Head Office (Kantor Pusat)', description: 'Kantor Pusat Alfa Tower Alam Sutera' },
  BRANCH_OFFICE: { code: 'BRANCH_OFFICE', label: 'Kantor Cabang (Branch Office)', description: 'Gedung Kantor Administrasi Cabang' },
  DC: { code: 'DC', label: 'Distribution Center (DC)', description: 'Pusat Distribusi Logistik Regional' },
  WAREHOUSE: { code: 'WAREHOUSE', label: 'Warehouse / Gudang Logistik', description: 'Gudang Utama (Dry/Chilled) & Bulky Storage' },
  DEPO: { code: 'DEPO', label: 'Depo / Transit Point', description: 'Titik Transit Pengiriman Logistik' },
  STORE_HUB: { code: 'STORE_HUB', label: 'Store Hub', description: 'Hub Penyangga Pasokan Toko Ritel' },
  STORE: { code: 'STORE', label: 'Jaringan Toko Ritel (Store)', description: 'Toko Ritel Alfamart / Toko Pilot PLTS' },
  OTHER: { code: 'OTHER', label: 'Fasilitas Lainnya', description: 'Fasilitas Pendukung Operasional' }
};

/**
 * 30 Verified Branch Operating Entities
 * Grid Factor Standard: Kepmen ESDM No. 379.K/2021
 */
export const BRANCH_LIST = [
  { id: 'BR-HO', code: 'HO-01', name: 'Head Office (Pusat Tangerang)', region: 'Banten', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-TGR1', code: 'BR-01', name: 'Cabang Tangerang 1 (Cikokol)', region: 'Banten', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-TGR2', code: 'BR-02', name: 'Cabang Tangerang 2 (Balaraja)', region: 'Banten', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-BGR1', code: 'BR-03', name: 'Cabang Bogor 1 (Cileungsi / Parung)', region: 'Jawa Barat', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-KRW', code: 'BR-04', name: 'Cabang Karawang', region: 'Jawa Barat', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-BDG1', code: 'BR-05', name: 'Cabang Bandung 1 (Gedebage)', region: 'Jawa Barat', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-BDG2', code: 'BR-06', name: 'Cabang Bandung 2 (Cimahi)', region: 'Jawa Barat', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-CJR', code: 'BR-07', name: 'Cabang Cianjur', region: 'Jawa Barat', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-CRB', code: 'BR-08', name: 'Cabang Cirebon (Plumbon)', region: 'Jawa Barat', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-SRG', code: 'BR-09', name: 'Cabang Serang', region: 'Banten', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-SMG', code: 'BR-10', name: 'Cabang Semarang', region: 'Jawa Tengah', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-KLT', code: 'BR-11', name: 'Cabang Klaten (Yogyakarta)', region: 'Jawa Tengah', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-RBG', code: 'BR-12', name: 'Cabang Rembang', region: 'Jawa Tengah', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-TGL', code: 'BR-13', name: 'Cabang Tegal', region: 'Jawa Tengah', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-CLP', code: 'BR-14', name: 'Cabang Cilacap', region: 'Jawa Tengah', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-SBY', code: 'BR-15', name: 'Cabang Surabaya (Sidoarjo)', region: 'Jawa Timur', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-MLG', code: 'BR-16', name: 'Cabang Malang', region: 'Jawa Timur', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-JBR', code: 'BR-17', name: 'Cabang Jember', region: 'Jawa Timur', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-MDN', code: 'BR-18', name: 'Cabang Madiun', region: 'Jawa Timur', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-BLI', code: 'BR-19', name: 'Cabang Bali (Gianyar)', region: 'Bali', gridRegion: 'JAMALI', gridFactor: 0.87 },
  { id: 'BR-LOP', code: 'BR-20', name: 'Cabang Lombok', region: 'Nusa Tenggara Barat', gridRegion: 'NTB_LOMBOK', gridFactor: 0.87 },
  { id: 'BR-MDN1', code: 'BR-21', name: 'Cabang Medan', region: 'Sumatera Utara', gridRegion: 'SUMATERA', gridFactor: 0.761 },
  { id: 'BR-PKU', code: 'BR-22', name: 'Cabang Pekanbaru', region: 'Riau', gridRegion: 'SUMATERA', gridFactor: 0.761 },
  { id: 'BR-BTH', code: 'BR-23', name: 'Cabang Batam', region: 'Kepulauan Riau', gridRegion: 'BATAM', gridFactor: 0.76 },
  { id: 'BR-DJB', code: 'BR-24', name: 'Cabang Jambi', region: 'Jambi', gridRegion: 'SUMATERA', gridFactor: 0.761 },
  { id: 'BR-PLM', code: 'BR-25', name: 'Cabang Palembang', region: 'Sumatera Selatan', gridRegion: 'SUMATERA', gridFactor: 0.761 },
  { id: 'BR-LPG', code: 'BR-26', name: 'Cabang Lampung & Kotabumi', region: 'Lampung', gridRegion: 'SUMATERA', gridFactor: 0.761 },
  { id: 'BR-PNK', code: 'BR-27', name: 'Cabang Pontianak', region: 'Kalimantan Barat', gridRegion: 'KALBAR', gridFactor: 0.95 },
  { id: 'BR-BDJ', code: 'BR-28', name: 'Cabang Banjarmasin', region: 'Kalimantan Selatan', gridRegion: 'KALSELTENG', gridFactor: 1.20 },
  { id: 'BR-MKS', code: 'BR-29', name: 'Cabang Makassar & Luwu', region: 'Sulawesi Selatan', gridRegion: 'SULSELRABAR', gridFactor: 0.73 },
  { id: 'BR-MDC', code: 'BR-30', name: 'Cabang Manado & Gorontalo', region: 'Sulawesi Utara', gridRegion: 'SULUTGO', gridFactor: 0.60 }
];

/**
 * Verified Physical Master Facilities (In-Memory Reference for Client/Offline Fallback)
 * Database (facility_master table) is the authoritative source for all runtime operations.
 */
export const MASTER_FACILITIES = [
  // ─── 1. HEAD OFFICE ────────────────────────────────────────────────────────
  {
    id: 'FAC-HO-ALFATOWER',
    code: 'HO-01',
    name: 'Alfa Tower Head Office',
    facilityType: 'HO',
    branchId: 'BR-HO',
    branchName: 'Head Office Corporate',
    region: 'Jabodetabek',
    province: 'Banten',
    city: 'Kota Tangerang',
    address: 'Jl. Jalur Sutera Barat Blok 15 No. 3, Alam Sutera, Tangerang',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'HO_MASTER_CORPORATE',
    sourceRef: 'Corporate Real Estate Registry 2026',
    hasPlts: false,
    linkedPlantDcId: null
  },

  // ─── 2. KANTOR CABANG UTAMA (VERIFIED BRANCH OFFICES) ──────────────────────
  {
    id: 'FAC-BR-TGR1',
    code: 'BR-TGR1-OFFICE',
    name: 'Kantor Cabang Tangerang 1 (Cikokol)',
    facilityType: 'BRANCH_OFFICE',
    branchId: 'BR-TGR1',
    branchName: 'Tangerang 1',
    region: 'Jabodetabek',
    province: 'Banten',
    city: 'Kota Tangerang',
    address: 'Jl. M.H. Thamrin No. 9, Cikokol, Tangerang',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'HO_MASTER_CORPORATE',
    sourceRef: 'Branch Office Directory 2026',
    hasPlts: false
  },
  {
    id: 'FAC-BR-TGR2',
    code: 'BR-TGR2-OFFICE',
    name: 'Kantor Cabang Tangerang 2 (Balaraja)',
    facilityType: 'BRANCH_OFFICE',
    branchId: 'BR-TGR2',
    branchName: 'Tangerang 2',
    region: 'Jabodetabek',
    province: 'Banten',
    city: 'Kabupaten Tangerang',
    address: 'Jl. Raya Serang Km. 24, Balaraja',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'HO_MASTER_CORPORATE',
    sourceRef: 'Branch Office Directory 2026',
    hasPlts: false
  },
  {
    id: 'FAC-BR-KRW',
    code: 'BR-KRW-OFFICE',
    name: 'Kantor Cabang Karawang',
    facilityType: 'BRANCH_OFFICE',
    branchId: 'BR-KRW',
    branchName: 'Karawang',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Karawang',
    address: 'Kawasan Surya Cipta, Karawang Timur',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'HO_MASTER_CORPORATE',
    sourceRef: 'Branch Office Directory 2026',
    hasPlts: false
  },

  // ─── 3. TOKO / STORE PILOT WITH ROOFTOP PLTS (VERIFIED) ────────────────────
  {
    id: 'FAC-STR-DEMANSION',
    code: 'STR-DTR-DEM',
    name: 'Toko Drive Thru De Mansion',
    facilityType: 'STORE',
    branchId: 'BR-TGR1',
    branchName: 'Tangerang 1',
    region: 'Jabodetabek',
    province: 'Banten',
    city: 'Kota Tangerang Selatan',
    address: 'Jl. Jalur Sutera Timur No. 1, Alam Sutera',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 6',
    hasPlts: true,
    linkedPlantDcId: 'Tk. Drive Thru De Mansion'
  },
  {
    id: 'FAC-STR-GS',
    code: 'STR-DTR-GS',
    name: 'Toko Drive Thru Gading Serpong',
    facilityType: 'STORE',
    branchId: 'BR-TGR1',
    branchName: 'Tangerang 1',
    region: 'Jabodetabek',
    province: 'Banten',
    city: 'Kabupaten Tangerang',
    address: 'Jl. Gading Serpong Boulevard Blok AA No. 12',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 18',
    hasPlts: true,
    linkedPlantDcId: 'Tk. Drive Thru GS'
  },

  // ─── 4. PHYSICAL DISTRIBUTION CENTERS (VERIFIED FROM MONITOR PLTS) ─────────
  {
    id: 'FAC-DC-BALARAJA',
    code: 'DC-BLR',
    name: 'DC Balaraja',
    facilityType: 'DC',
    branchId: 'BR-TGR2',
    branchName: 'Tangerang 2',
    region: 'Jabodetabek',
    province: 'Banten',
    city: 'Kabupaten Tangerang',
    address: 'Kawasan Industri Olex, Balaraja, Tangerang',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 35',
    hasPlts: true,
    linkedPlantDcId: 'Balaraja'
  },
  {
    id: 'FAC-DC-CILEUNGSI',
    code: 'DC-CLS',
    name: 'DC Cileungsi',
    facilityType: 'DC',
    branchId: 'BR-BGR1',
    branchName: 'Bogor 1',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Bogor',
    address: 'Jl. Raya Narogong Km. 21, Cileungsi, Bogor',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 3',
    hasPlts: true,
    linkedPlantDcId: 'Cileungsi'
  },
  {
    id: 'FAC-DC-KARAWANG',
    code: 'DC-KRW',
    name: 'DC Karawang',
    facilityType: 'DC',
    branchId: 'BR-KRW',
    branchName: 'Karawang',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Karawang',
    address: 'Kawasan Industri Surya Cipta, Karawang Timur',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 39',
    hasPlts: true,
    linkedPlantDcId: 'Karawang'
  },
  {
    id: 'FAC-DC-PARUNG',
    code: 'DC-PRG',
    name: 'DC Parung',
    facilityType: 'DC',
    branchId: 'BR-BGR1',
    branchName: 'Bogor 1',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Bogor',
    address: 'Jl. Raya Parung - Bogor Km. 27',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 30',
    hasPlts: true,
    linkedPlantDcId: 'Parung'
  },
  {
    id: 'FAC-DC-BOGOR',
    code: 'DC-BGR',
    name: 'DC Bogor',
    facilityType: 'DC',
    branchId: 'BR-BGR1',
    branchName: 'Bogor 1',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kota Bogor',
    address: 'Kawasan Industri Kedunghalang, Bogor',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 29',
    hasPlts: true,
    linkedPlantDcId: 'Bogor'
  },
  {
    id: 'FAC-DC-SERANG',
    code: 'DC-SRG',
    name: 'DC Serang',
    facilityType: 'DC',
    branchId: 'BR-SRG',
    branchName: 'Serang',
    region: 'Banten',
    province: 'Banten',
    city: 'Kabupaten Serang',
    address: 'Jl. Raya Serang - Jakarta Km. 68, Kragilan',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 10',
    hasPlts: true,
    linkedPlantDcId: 'Serang'
  },
  {
    id: 'FAC-DC-BANDUNG1',
    code: 'DC-BDG1',
    name: 'DC Bandung 1',
    facilityType: 'DC',
    branchId: 'BR-BDG1',
    branchName: 'Bandung 1',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kota Bandung',
    address: 'Jl. Soekarno Hatta No. 791, Gedebage, Bandung',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 32',
    hasPlts: true,
    linkedPlantDcId: 'Bandung 1'
  },
  {
    id: 'FAC-DC-BANDUNG2',
    code: 'DC-BDG2',
    name: 'DC Bandung 2',
    facilityType: 'DC',
    branchId: 'BR-BDG2',
    branchName: 'Bandung 2',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Bandung Barat',
    address: 'Kawasan Industri Batujajar, Cimahi',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 11',
    hasPlts: true,
    linkedPlantDcId: 'Bandung 2'
  },
  {
    id: 'FAC-DC-CIANJUR',
    code: 'DC-CJR',
    name: 'DC Cianjur',
    facilityType: 'DC',
    branchId: 'BR-CJR',
    branchName: 'Cianjur',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Cianjur',
    address: 'Jl. Raya Bandung Km. 9, Sukaluyu, Cianjur',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 15',
    hasPlts: true,
    linkedPlantDcId: 'Cianjur'
  },
  {
    id: 'FAC-DC-PLUMBON',
    code: 'DC-PLB',
    name: 'DC Plumbon',
    facilityType: 'DC',
    branchId: 'BR-CRB',
    branchName: 'Cirebon',
    region: 'Jawa Barat',
    province: 'Jawa Barat',
    city: 'Kabupaten Cirebon',
    address: 'Jl. Raya Plumbon - Cirebon Km. 12',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 7',
    hasPlts: true,
    linkedPlantDcId: 'Plumbon'
  },
  {
    id: 'FAC-DC-SEMARANG',
    code: 'DC-SMG',
    name: 'DC Semarang',
    facilityType: 'DC',
    branchId: 'BR-SMG',
    branchName: 'Semarang',
    region: 'Jawa Tengah',
    province: 'Jawa Tengah',
    city: 'Kota Semarang',
    address: 'Kawasan Industri Candi, Ngaliyan, Semarang',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 16',
    hasPlts: true,
    linkedPlantDcId: 'Semarang'
  },
  {
    id: 'FAC-DC-TEGAL',
    code: 'DC-TGL',
    name: 'DC Tegal',
    facilityType: 'DC',
    branchId: 'BR-TGL',
    branchName: 'Tegal',
    region: 'Jawa Tengah',
    province: 'Jawa Tengah',
    city: 'Kabupaten Tegal',
    address: 'Jl. Raya Dampyak Km. 4, Kramat, Tegal',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 4',
    hasPlts: true,
    linkedPlantDcId: 'Tegal'
  },
  {
    id: 'FAC-DC-KLATEN',
    code: 'DC-KLT',
    name: 'DC Klaten',
    facilityType: 'DC',
    branchId: 'BR-KLT',
    branchName: 'Klaten',
    region: 'Jawa Tengah',
    province: 'Jawa Tengah',
    city: 'Kabupaten Klaten',
    address: 'Jl. Raya Jogja - Solo Km. 24, Ceper, Klaten',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 17',
    hasPlts: true,
    linkedPlantDcId: 'Klaten'
  },
  {
    id: 'FAC-DC-REMBANG',
    code: 'DC-RBG',
    name: 'DC Rembang',
    facilityType: 'DC',
    branchId: 'BR-RBG',
    branchName: 'Rembang',
    region: 'Jawa Tengah',
    province: 'Jawa Tengah',
    city: 'Kabupaten Rembang',
    address: 'Jl. Raya Rembang - Blora Km. 5, Rembang',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 34',
    hasPlts: true,
    linkedPlantDcId: 'Rembang'
  },
  {
    id: 'FAC-DC-CILACAP',
    code: 'DC-CLP',
    name: 'DC Cilacap (Kompleks)',
    facilityType: 'DC',
    branchId: 'BR-CLP',
    branchName: 'Cilacap',
    region: 'Jawa Tengah',
    province: 'Jawa Tengah',
    city: 'Kabupaten Cilacap',
    address: 'Jl. Raya Tritih Kulon, Cilacap Utara',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Rows 12, 13, 14 (Plants Cilacap 1, 2, 3)',
    hasPlts: true,
    linkedPlantDcId: 'Cilacap 1'
  },
  {
    id: 'FAC-DC-SIDOARJO',
    code: 'DC-SDA',
    name: 'DC Sidoarjo (Surabaya)',
    facilityType: 'DC',
    branchId: 'BR-SBY',
    branchName: 'Surabaya / Sidoarjo',
    region: 'Jawa Timur',
    province: 'Jawa Timur',
    city: 'Kabupaten Sidoarjo',
    address: 'Kawasan Industri SIER - Gedangan, Sidoarjo',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 5',
    hasPlts: true,
    linkedPlantDcId: 'Sidoarjo'
  },
  {
    id: 'FAC-DC-MALANG',
    code: 'DC-MLG',
    name: 'DC Malang',
    facilityType: 'DC',
    branchId: 'BR-MLG',
    branchName: 'Malang',
    region: 'Jawa Timur',
    province: 'Jawa Timur',
    city: 'Kabupaten Malang',
    address: 'Jl. Raya Karanglo No. 88, Singosari, Malang',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 31',
    hasPlts: true,
    linkedPlantDcId: 'Malang'
  },
  {
    id: 'FAC-DC-JEMBER',
    code: 'DC-JBR',
    name: 'DC Jember',
    facilityType: 'DC',
    branchId: 'BR-JBR',
    branchName: 'Jember',
    region: 'Jawa Timur',
    province: 'Jawa Timur',
    city: 'Kabupaten Jember',
    address: 'Jl. Brawijaya No. 77, Jubung, Jember',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 8',
    hasPlts: true,
    linkedPlantDcId: 'Jember'
  },
  {
    id: 'FAC-DC-MADIUN',
    code: 'DC-MDN',
    name: 'DC Madiun',
    facilityType: 'DC',
    branchId: 'BR-MDN',
    branchName: 'Madiun',
    region: 'Jawa Timur',
    province: 'Jawa Timur',
    city: 'Kabupaten Madiun',
    address: 'Jl. Raya Caruban - Madiun Km. 6, Balerejo',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 9',
    hasPlts: true,
    linkedPlantDcId: 'Madiun'
  },
  {
    id: 'FAC-DC-BALI',
    code: 'DC-BLI',
    name: 'DC Bali',
    facilityType: 'DC',
    branchId: 'BR-BLI',
    branchName: 'Bali',
    region: 'Bali & Nusra',
    province: 'Bali',
    city: 'Kabupaten Gianyar',
    address: 'Jl. Bypass Prof. Dr. Ida Bagus Mantra, Gianyar',
    gridRegion: 'JAMALI',
    gridFactor: 0.87,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 33',
    hasPlts: true,
    linkedPlantDcId: 'Bali'
  },
  {
    id: 'FAC-DC-LOMBOK',
    code: 'DC-LOP',
    name: 'DC Lombok (Kompleks)',
    facilityType: 'DC',
    branchId: 'BR-LOP',
    branchName: 'Lombok',
    region: 'Bali & Nusra',
    province: 'Nusa Tenggara Barat',
    city: 'Kabupaten Lombok Barat',
    address: 'Jl. TGH Lopan, Labuapi, Lombok Barat',
    gridRegion: 'NTB_LOMBOK',
    gridFactor: 0.87,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Rows 26, 27 (Plants Lombok A & B)',
    hasPlts: true,
    linkedPlantDcId: 'Lombok A'
  },
  {
    id: 'FAC-DC-MEDAN',
    code: 'DC-KNO',
    name: 'DC Medan',
    facilityType: 'DC',
    branchId: 'BR-MDN1',
    branchName: 'Medan',
    region: 'Sumatera',
    province: 'Sumatera Utara',
    city: 'Kabupaten Deli Serdang',
    address: 'Kawasan Industri KIM 2, Mabar, Deli Serdang',
    gridRegion: 'SUMATERA',
    gridFactor: 0.761,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 36',
    hasPlts: true,
    linkedPlantDcId: 'Medan'
  },
  {
    id: 'FAC-DC-PEKANBARU',
    code: 'DC-PKU',
    name: 'DC Pekanbaru',
    facilityType: 'DC',
    branchId: 'BR-PKU',
    branchName: 'Pekanbaru',
    region: 'Sumatera',
    province: 'Riau',
    city: 'Kota Pekanbaru',
    address: 'Jl. SM Amin / Arengka 2, Pekanbaru',
    gridRegion: 'SUMATERA',
    gridFactor: 0.761,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 22',
    hasPlts: true,
    linkedPlantDcId: 'Pekanbaru'
  },
  {
    id: 'FAC-DC-BATAM',
    code: 'DC-BTH',
    name: 'DC Batam',
    facilityType: 'DC',
    branchId: 'BR-BTH',
    branchName: 'Batam',
    region: 'Sumatera',
    province: 'Kepulauan Riau',
    city: 'Kota Batam',
    address: 'Kawasan Industri Batamindo, Mukakuning, Batam',
    gridRegion: 'BATAM',
    gridFactor: 0.76,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 23',
    hasPlts: true,
    linkedPlantDcId: 'Batam'
  },
  {
    id: 'FAC-DC-JAMBI',
    code: 'DC-DJB',
    name: 'DC Jambi',
    facilityType: 'DC',
    branchId: 'BR-DJB',
    branchName: 'Jambi',
    region: 'Sumatera',
    province: 'Jambi',
    city: 'Kabupaten Muaro Jambi',
    address: 'Jl. Lintas Timur Sumatera Km. 28, Muaro Jambi',
    gridRegion: 'SUMATERA',
    gridFactor: 0.761,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 24',
    hasPlts: true,
    linkedPlantDcId: 'Jambi'
  },
  {
    id: 'FAC-DC-PALEMBANG',
    code: 'DC-PLM',
    name: 'DC Palembang',
    facilityType: 'DC',
    branchId: 'BR-PLM',
    branchName: 'Palembang',
    region: 'Sumatera',
    province: 'Sumatera Selatan',
    city: 'Kota Palembang',
    address: 'Jl. Bypass Alang-Alang Lebar, Palembang',
    gridRegion: 'SUMATERA',
    gridFactor: 0.761,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 37',
    hasPlts: true,
    linkedPlantDcId: 'Palembang'
  },
  {
    id: 'FAC-DC-LAMPUNG',
    code: 'DC-TKG',
    name: 'DC Lampung',
    facilityType: 'DC',
    branchId: 'BR-LPG',
    branchName: 'Lampung',
    region: 'Sumatera',
    province: 'Lampung',
    city: 'Kabupaten Lampung Selatan',
    address: 'Jl. Raya Branti Km. 28, Natar, Lampung Selatan',
    gridRegion: 'SUMATERA',
    gridFactor: 0.761,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 28',
    hasPlts: true,
    linkedPlantDcId: 'Lampung'
  },
  {
    id: 'FAC-DC-KOTABUMI',
    code: 'DC-KTB',
    name: 'DC Kotabumi',
    facilityType: 'DC',
    branchId: 'BR-LPG',
    branchName: 'Lampung',
    region: 'Sumatera',
    province: 'Lampung',
    city: 'Kabupaten Lampung Utara',
    address: 'Jl. Lintas Tengah Sumatera, Kotabumi',
    gridRegion: 'SUMATERA',
    gridFactor: 0.761,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 19',
    hasPlts: true,
    linkedPlantDcId: 'Kotabumi'
  },
  {
    id: 'FAC-DC-PONTIANAK',
    code: 'DC-PNK',
    name: 'DC Pontianak',
    facilityType: 'DC',
    branchId: 'BR-PNK',
    branchName: 'Pontianak',
    region: 'Kalimantan',
    province: 'Kalimantan Barat',
    city: 'Kabupaten Kubu Raya',
    address: 'Jl. Arteri Supadio Km. 14, Kubu Raya',
    gridRegion: 'KALBAR',
    gridFactor: 0.95,
    timezone: 'Asia/Jakarta',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 25',
    hasPlts: true,
    linkedPlantDcId: 'Pontianak'
  },
  {
    id: 'FAC-DC-BANJARMASIN',
    code: 'DC-BDJ',
    name: 'DC Banjarmasin',
    facilityType: 'DC',
    branchId: 'BR-BDJ',
    branchName: 'Banjarmasin',
    region: 'Kalimantan',
    province: 'Kalimantan Selatan',
    city: 'Kabupaten Banjar',
    address: 'Jl. Gubernur Soebardjo, Kertak Hanyar, Banjar',
    gridRegion: 'KALSELTENG',
    gridFactor: 1.20,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 38',
    hasPlts: true,
    linkedPlantDcId: 'Banjarmasin'
  },
  {
    id: 'FAC-DC-MAKASSAR',
    code: 'DC-UPG',
    name: 'DC Makassar (Maros)',
    facilityType: 'DC',
    branchId: 'BR-MKS',
    branchName: 'Makassar',
    region: 'Sulawesi',
    province: 'Sulawesi Selatan',
    city: 'Kabupaten Maros',
    address: 'Kawasan Industri KIMA 8, Maros - Makassar',
    gridRegion: 'SULSELRABAR',
    gridFactor: 0.73,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 20',
    hasPlts: true,
    linkedPlantDcId: 'Makassar'
  },
  {
    id: 'FAC-DC-LUWU',
    code: 'DC-LUW',
    name: 'DC Luwu',
    facilityType: 'DC',
    branchId: 'BR-MKS',
    branchName: 'Makassar',
    region: 'Sulawesi',
    province: 'Sulawesi Selatan',
    city: 'Kabupaten Luwu',
    address: 'Jl. Trans Sulawesi, Belopa, Luwu',
    gridRegion: 'SULSELRABAR',
    gridFactor: 0.73,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 2',
    hasPlts: true,
    linkedPlantDcId: 'Luwu'
  },
  {
    id: 'FAC-DC-MANADO',
    code: 'DC-MDC',
    name: 'DC Manado',
    facilityType: 'DC',
    branchId: 'BR-MDC',
    branchName: 'Manado',
    region: 'Sulawesi',
    province: 'Sulawesi Utara',
    city: 'Kabupaten Minahasa Utara',
    address: 'Jl. Raya Manado - Bitung Km. 18, Kauditan',
    gridRegion: 'SULUTGO',
    gridFactor: 0.60,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 21',
    hasPlts: true,
    linkedPlantDcId: 'Manado'
  },
  {
    id: 'FAC-DC-GORONTALO',
    code: 'DC-GTO',
    name: 'DC Gorontalo',
    facilityType: 'DC',
    branchId: 'BR-MDC',
    branchName: 'Manado',
    region: 'Sulawesi',
    province: 'Gorontalo',
    city: 'Kabupaten Bone Bolango',
    address: 'Jl. Trans Sulawesi, Suwawa, Bone Bolango',
    gridRegion: 'SULUTGO',
    gridFactor: 0.60,
    timezone: 'Asia/Makassar',
    isActive: true,
    verificationStatus: 'VERIFIED',
    sourceMaster: 'MONITOR_PLTS_WORKBOOK',
    sourceRef: 'Monitor PLTS 2026 Sheet APRIL 2026 Row 1',
    hasPlts: true,
    linkedPlantDcId: 'Gorontalo'
  }
];

/**
 * Filter verified facilities for UI selector and validation
 */
export function getFilteredFacilities({
  facilityType = 'all',
  branchId = 'all',
  searchQuery = '',
  hasPltsOnly = false,
  includeUnverified = false
} = {}) {
  return MASTER_FACILITIES.filter(fac => {
    if (!includeUnverified && fac.verificationStatus !== 'VERIFIED') return false;
    if (facilityType !== 'all' && fac.facilityType !== facilityType) return false;
    if (branchId !== 'all' && fac.branchId !== branchId) return false;
    if (hasPltsOnly && !fac.hasPlts) return false;
    if (searchQuery) {
      const q = searchQuery.toLowerCase().trim();
      const matchName = fac.name.toLowerCase().includes(q);
      const matchCode = fac.code.toLowerCase().includes(q);
      const matchRegion = (fac.region || '').toLowerCase().includes(q);
      const matchCity = (fac.city || '').toLowerCase().includes(q);
      if (!matchName && !matchCode && !matchRegion && !matchCity) return false;
    }
    return true;
  });
}

/**
 * Find single verified facility by ID, Code, or Alias
 */
export function findFacilityById(idOrCode) {
  if (!idOrCode) return null;
  const target = String(idOrCode).trim().toLowerCase();
  return MASTER_FACILITIES.find(f => 
    f.id.toLowerCase() === target ||
    f.code.toLowerCase() === target ||
    f.name.toLowerCase() === target ||
    (f.linkedPlantDcId && f.linkedPlantDcId.toLowerCase() === target)
  ) || null;
}
